# My Study Notebook about Nibabel
Nibabel is python library for using NIfTI file I/O

## 1. reference
1. https://nipy.org/nibabel/index.html
2. https://nipy.org/nibabel/reference/nibabel.nifti1.html#nibabel.nifti1.Nifti1Pair.get_qform
3. https://nipy.org/nibabel/nifti_images.html

## 2. Preparation
you need 'Nibabel' Library

If you have macOS, command 'pip install nibabel' on anaconda environment.

In [1]:
import os
import nibabel as nib
from nibabel.testing import data_path

# Lording NIfTI file 

1. use nibabel.load

In [2]:
example_ni1 = os.path.join(data_path, 'example4d.nii.gz')
n1_img = nib.load(example_ni1)

In [3]:
example_ni2 = os.path.join(data_path, 'example_nifti2.nii.gz')
n2_img = nib.load(example_ni2)

## preview Header infomation

1. nibabel.load image obeject
2. use method header

In [4]:
n1_header = n1_img.header
print(n1_header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 57
dim             : [  4 128  96  24   2   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [-1.000000e+00  2.000000e+00  2.000000e+00  2.199999e+00  2.000000e+03
  1.000000e+00  1.000000e+00  1.000000e+00]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 23
slice_code      : unknown
xyzt_units      : 10
cal_max         : 1162.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'FSL3.3\x00 v2.25 NIfTI-1 Single file format'
aux_file        : b''
qform_code      : scanner
sform_code      : scanner
quatern_b       : -1.9451068e-26
quatern_c       :

In [5]:
n2_header = n2_img.header
print(n2_header)

<class 'nibabel.nifti2.Nifti2Header'> object, endian='<'
sizeof_hdr      : 540
magic           : b'n+2'
eol_check       : [13 10 26 10]
datatype        : int16
bitpix          : 16
dim             : [ 4 32 20 12  2  1  1  1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
pixdim          : [-1.00000000e+00  2.00000000e+00  2.00000000e+00  2.19999909e+00
  2.00000000e+03  1.00000000e+00  1.00000000e+00  1.00000000e+00]
vox_offset      : 0
scl_slope       : nan
scl_inter       : nan
cal_max         : 1162.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
slice_start     : 0
slice_end       : 23
descrip         : b'FSL3.3\x00 v2.25 NIfTI-1 Single file format'
aux_file        : b''
qform_code      : scanner
sform_code      : scanner
quatern_b       : -1.9451068140294884e-26
quatern_c       : -0.9967085123062134
quatern_d       : -0.0810687392950058
qoffset_x       : 117.8551025390625
qoffset_y       : -35.72294235229492
qoffset_z       : -7.2487983703613

## Lording data 

1. get data from .get_data()
2. data type is numpy array

In [6]:
img_data = n1_img.get_data()

In [7]:
print(img_data.shape)

(128, 96, 24, 2)


## Check The voxel orientations　infomation
aff2axcodes is Used for Check The voxel orientations infomation

### Example 

In [8]:
nib.aff2axcodes(n1_img.affine)

('L', 'A', 'S')

'L' means : First voxel axis goes from right to Left;  
'A' means : Second voxel axis goes from posterior to Anterior;  
'S' means :Third voxel axis goes from inferior to Superior.  

# get Affine matrics

check:Official Document
https://nipy.org/nibabel/nifti_images.html

In [9]:
affine=n1_img.affine

In [10]:
affine

array([[-2.00000000e+00,  6.71471565e-19,  9.08102451e-18,
         1.17855103e+02],
       [-6.71471565e-19,  1.97371149e+00, -3.55528235e-01,
        -3.57229424e+01],
       [ 8.25548089e-18,  3.23207617e-01,  2.17108178e+00,
        -7.24879837e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

## get sform affine

| Code |	Label |	Meaning |
|:---|:------:|:-----:|
| 0 | unknown | sform not defined |  
| 1 | scanner | RAS+ in scanner coordinates |
| 2 | aligned | RAS+ aligned to some other scan |  
| 3 | talairach | RAS+ in Talairach atlas space |
| 4 | mni | RAS+ in MNI atlas space |
 


In [11]:
print(n1_header['sform_code'])
print(n1_header.get_sform())

1
[[-2.00000000e+00  6.71471565e-19  9.08102451e-18  1.17855103e+02]
 [-6.71471565e-19  1.97371149e+00 -3.55528235e-01 -3.57229424e+01]
 [ 8.25548089e-18  3.23207617e-01  2.17108178e+00 -7.24879837e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


## get qform affine

In [12]:
print(n1_header.get_qform(coded=True))

(array([[-2.00000000e+00,  1.02823968e-05,  1.39059804e-04,
         1.17855103e+02],
       [-1.02823968e-05,  1.97371144e+00, -3.55528225e-01,
        -3.57229424e+01],
       [ 1.26418055e-04,  3.23207610e-01,  2.17108168e+00,
        -7.24879837e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]]), 1)


## get the fall-back header affine

In [13]:
print(n1_header.get_base_affine())

[[ -2.           0.           0.         127.        ]
 [  0.           2.           0.         -95.        ]
 [  0.           0.           2.19999909 -25.29998958]
 [  0.           0.           0.           1.        ]]


## Save NIfTI file

In [14]:
nii_file = nib.Nifti1Image(img_data, affine=affine)
nib.save(nii_file , 'nii_file.nii')

In [15]:
nifti = nib.load('nii_file.nii')